Loading sparse matrices from ./../data/preprocessed/imdb/imdb.title.basics.tsv.filtered.mt75.ts3/teamsvecs.pkl ...
Loading indexes pickle from ./../data/preprocessed/imdb/imdb.title.basics.tsv.filtered.mt75.ts3/indexes.pkl ...
It took 0.011927366256713867 seconds to load from the pickles.
It took 0.20420360565185547 seconds to load the sparse matrices.

8 GPUs detected. Using GPUs: 6,7 .

Using device: cuda
Running for (dataset, model): (imdb, nmt_imdb_transformer-abs-wv256) ... 
Executing command: onmt_translate -model ./../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/fold0/model_step_400.pt -src ./../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/src-test.txt -output ./../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/fold0/test.fold0.epoch400.pred.csv -gpu 0 --min_length 2 -verbose 
Error executing command: Command '['onmt_translate', '-model', './../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/fold0/model_step_400.pt', '-src', './../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/src-test.txt', '-output', './../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/fold0/test.fold0.epoch400.pred.csv', '-gpu', '0', '--min_length', '2', '-verbose']' returned non-zero exit status 1.
Command output: 
Command error: Traceback (most recent call last):
  File "/usr/local/bin/onmt_translate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/onmt/bin/translate.py", line 60, in main
    translate(opt)
  File "/usr/local/lib/python3.8/dist-packages/onmt/bin/translate.py", line 23, in translate
    translator = build_translator(opt, logger=logger,
  File "/usr/local/lib/python3.8/dist-packages/onmt/translate/translator.py", line 31, in build_translator
    vocabs, model, model_opt = load_test_model(opt)
  File "/usr/local/lib/python3.8/dist-packages/onmt/model_builder.py", line 91, in load_test_model
    checkpoint = torch.load(model_path,
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/fold0/model_step_400.pt'

Executing command: onmt_translate -model ./../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/fold1/model_step_400.pt -src ./../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/src-test.txt -output ./../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/fold1/test.fold1.epoch400.pred.csv -gpu 0 --min_length 2 -verbose 
Error executing command: Command '['onmt_translate', '-model', './../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/fold1/model_step_400.pt', '-src', './../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/src-test.txt', '-output', './../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/fold1/test.fold1.epoch400.pred.csv', '-gpu', '0', '--min_length', '2', '-verbose']' returned non-zero exit status 1.
Command output: 
Command error: Traceback (most recent call last):
  File "/usr/local/bin/onmt_translate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/onmt/bin/translate.py", line 60, in main
    translate(opt)
  File "/usr/local/lib/python3.8/dist-packages/onmt/bin/translate.py", line 23, in translate
    translator = build_translator(opt, logger=logger,
  File "/usr/local/lib/python3.8/dist-packages/onmt/translate/translator.py", line 31, in build_translator
    vocabs, model, model_opt = load_test_model(opt)
  File "/usr/local/lib/python3.8/dist-packages/onmt/model_builder.py", line 91, in load_test_model
    checkpoint = torch.load(model_path,
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/fold1/model_step_400.pt'

Executing command: onmt_translate -model ./../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/fold2/model_step_400.pt -src ./../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/src-test.txt -output ./../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/fold2/test.fold2.epoch400.pred.csv -gpu 0 --min_length 2 -verbose 
Error executing command: Command '['onmt_translate', '-model', './../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/fold2/model_step_400.pt', '-src', './../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/src-test.txt', '-output', './../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/fold2/test.fold2.epoch400.pred.csv', '-gpu', '0', '--min_length', '2', '-verbose']' returned non-zero exit status 1.
Command output: 
Command error: Traceback (most recent call last):
  File "/usr/local/bin/onmt_translate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/onmt/bin/translate.py", line 60, in main
    translate(opt)
  File "/usr/local/lib/python3.8/dist-packages/onmt/bin/translate.py", line 23, in translate
    translator = build_translator(opt, logger=logger,
  File "/usr/local/lib/python3.8/dist-packages/onmt/translate/translator.py", line 31, in build_translator
    vocabs, model, model_opt = load_test_model(opt)
  File "/usr/local/lib/python3.8/dist-packages/onmt/model_builder.py", line 91, in load_test_model
    checkpoint = torch.load(model_path,
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './../output/imdb.title.basics.tsv.filtered.mt75.ts3/nmt_imdb_transformer-abs-wv256.l512.wv256.lr0.0013.b80.e1/fold2/model_step_400.pt'

